apiVersion: v1
kind: PersistentVolume
metadata: 
  name: derecho-cfgs-pv
  labels: 
    pv: derecho-cfgs-pv
spec:
  capacity:
    storage: 1Mi
  accessModes:
  - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /home1/root/derecho-docker/derecho-dev/k8s-config
    server: 10.0.0.252